version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    #image: bitnami/kafka:latest
    image: bitnami/kafka:3.4.0
    ports:
      - "9092:9092"
    environment:
      #KAFKA_BROKER_ID: 1
      #KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      #KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      #KAFKA_CFG_PROCESS_ROLES: broker
      #KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ""
      #KAFKA_ENABLE_KRAFT: "no"
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT 
      #ALLOW_PLAINTEXT_LISTENER: "yes"

      KAFKA_ENABLE_KRAFT: "no"  # Important to explicitly disable KRaft
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - db
volumes:
  grafana-storage:
